In [92]:
# Solve a linear system using 3 different approaches : Gaussian elimination, Inverse , PLU factorization & measure times.

import numpy as np
from scipy.linalg import solve_triangular
from numpy.linalg import inv
from scipy.linalg import lu
import time


def gaussElim(Matrix):
    j = 1
    num_rows, num_cols = Matrix.shape
    for i in range(0,num_rows):
        Matrix[i] = Matrix[i]/Matrix[i,i]
        while( j < num_rows):
            Matrix[j] = Matrix[j] - Matrix[j,i]*Matrix[i]
            j+=1
        i+=1
        j = i+ 1
    A = Matrix[0:10,0:10]
    B = Matrix[0:,10:]
    X1 = solve_triangular(A, B, unit_diagonal = True)
    return(X1)


def pluTrans(upper,lower,perm,b):
    RHS1 = perm.T.dot(b)
    Y = solve_triangular(lower, RHS1, lower=True)
    X = solve_triangular(upper, Y)
    return(X)  


A_ORIG = np.array([[20, 37, 38, 23, 19, 31, 35, 29, 21, 30],
              [39, 13, 12, 29, 12, 16, 39, 36, 18, 18],
              [38, 42, 12, 39, 17, 22, 43, 38, 29, 24],
              [26, 23, 17, 42, 23, 18, 22, 35, 38, 24],
              [24, 21, 42, 19, 32, 12, 26, 24, 39, 22],
              [36, 18, 41, 14, 26, 19, 44, 22, 20, 27],
              [26, 36, 21, 42, 42, 33, 22, 34, 13, 21],
              [15, 25, 28, 22, 44, 44, 25, 18, 15, 35],
              [39, 43, 19, 27, 14, 34, 16, 25, 37, 13],
              [25, 35, 31, 18, 43, 20, 37, 14, 26, 14]])

b1 = np.array([[447],
              [310],
              [313],
              [486],
              [396],
              [317],
              [320],
              [342],
              [445],
              [487]])

b2 = np.array([[223],
       [498],
       [416],
       [370],
       [260],
       [295],
       [417],
       [290],
       [341],
       [220]])

b3 = np.array([[443],
       [350],
       [763],
       [556],
       [641],
       [347],
       [749],
       [563],
       [735],
       [248]])

# 1- Convert A to an Upper triangular matrix & then solve for X using  solve triangular
tic1 = time.perf_counter()
augMatrix1 = np.column_stack((A_ORIG,b1)).astype(float)
X1 = gaussElim(augMatrix1)
augMatrix2 = np.column_stack((A_ORIG,b2)).astype(float)
X2 = gaussElim(augMatrix2)
augMatrix3 = np.column_stack((A_ORIG,b3)).astype(float)
X3 = gaussElim(augMatrix3)
toc1 = time.perf_counter()
X = np.column_stack((X1,X2,X3))
print(X)
print("\nGaussian Elimination took %s seconds\n" % (toc1-tic1))

# 2- get inv of A & then find B
tic1 = time.perf_counter()
Ainv = inv(A_ORIG)
X1 = Ainv.dot(b1)
X2 = Ainv.dot(b2)
X3 = Ainv.dot(b3)
toc1 = time.perf_counter()
X = np.column_stack((X1,X2,X3))
print(X)
print("\nInverse method took %s seconds\n" % (toc1-tic1))
#3 - A = LU factorization
tic1 = time.perf_counter()
plu = lu(A_ORIG, permute_l=False, overwrite_a=False, check_finite=True)
perm = plu[0]
lower =plu[1]
upper = plu[2]
X1 = pluTrans(upper,lower,perm,b1)
X2 = pluTrans(upper,lower,perm,b2)
X3 = pluTrans(upper,lower,perm,b3)
toc1 = time.perf_counter()
X = np.column_stack((X1,X2,X3))
print(X)
print("\nPLU factorization took %s seconds\n" % (toc1-tic1))

[[-12.10710752   4.64768699  21.01075846]
 [-11.34348998  -3.24316455  26.12626291]
 [ 12.1989702   -4.42425461 -19.52210838]
 [ 23.00743905  -5.40344451 -43.70383888]
 [ -7.97915438   4.63676968  20.14006475]
 [ 18.75807823   3.5417007  -24.57978448]
 [ 16.05216641  -0.13794706 -33.45692627]
 [-13.44692544  13.24388917  40.58170632]
 [ 11.31479883   1.07385421  -3.30663376]
 [-24.10843133  -1.90808919  41.53386166]]

Gaussian Elimination took 0.0018024509990937077 seconds

[[-12.10710752   4.64768699  21.01075846]
 [-11.34348998  -3.24316455  26.12626291]
 [ 12.1989702   -4.42425461 -19.52210838]
 [ 23.00743905  -5.40344451 -43.70383888]
 [ -7.97915438   4.63676968  20.14006475]
 [ 18.75807823   3.5417007  -24.57978448]
 [ 16.05216641  -0.13794706 -33.45692627]
 [-13.44692544  13.24388917  40.58170632]
 [ 11.31479883   1.07385421  -3.30663376]
 [-24.10843133  -1.90808919  41.53386166]]

Inverse method took 0.00022643499687546864 seconds

[[-12.10710752   4.64768699  21.01075846]
 [-11

In [40]:
#RREF form
import numpy as np
import sympy as sp
from sympy import init_printing
init_printing()
M = np.rint(np.random.randn(20,30)*100)
M1 =sp.Matrix(M)
K = M1.rref()
K

⎛⎡1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0.33916599820647
⎜⎢                                                                            
⎜⎢0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  -0.6591539518002
⎜⎢                                                                            
⎜⎢0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0.65835598959808
⎜⎢                                                                            
⎜⎢0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  -0.2511506051548
⎜⎢                                                                            
⎜⎢0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  -4.4292201056531
⎜⎢                                                                            
⎜⎢0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  -0.4290308532910
⎜⎢                                                                            
⎜⎢0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0 

In [58]:
# A = QR factorization

import numpy as np
from scipy import linalg
M = np.rint(np.random.randn(20,20)*100)
q,r = linalg.qr(M)
print(q)
print(r)
col1 = q[0:19,0:1]
k = np.square(col1)
print(sum(k))

[[-2.33618717e-02  1.56981091e-01 -1.20153077e-01  1.65975704e-01
   2.45752002e-01 -1.54713021e-01  4.77524022e-03  4.62913032e-02
   8.16701642e-02 -3.21646050e-01 -3.42885645e-01  1.61431956e-02
   1.48236486e-01 -5.59152507e-01  2.45843649e-01  2.11288880e-01
  -2.39052852e-02  1.67621495e-01 -2.90123206e-01 -2.56565136e-01]
 [-2.92023396e-02 -2.36778526e-01 -3.30396989e-01 -8.01047483e-02
  -4.27299152e-01 -1.97506028e-01 -1.44670939e-01  1.32975861e-01
   5.51915939e-02 -3.36639497e-01 -2.61979512e-01  1.32712273e-01
  -3.63420360e-01  8.37874782e-02 -1.08183755e-01 -2.61542217e-01
   1.44911652e-01  1.84920479e-01  1.35816579e-01 -2.68023900e-01]
 [ 2.33618717e-01  3.20160117e-01  2.12345329e-02 -3.97566528e-01
  -2.18914066e-01 -2.10590547e-01  4.29934950e-01 -2.93668642e-01
  -1.03082230e-01 -3.14195332e-01  3.37164071e-01  5.39409667e-02
   9.92154189e-02 -1.73216310e-01  5.56725061e-02 -2.42210169e-02
   2.44813058e-02  5.41257769e-02  2.14094482e-01 -4.71138812e-02]
 [-3.35

In [33]:
# diagonalize a matrix & get power

import numpy as np
from scipy import linalg as LA
from numpy.linalg import matrix_power
import sympy as sp
from sympy import init_printing
init_printing()
M = np.rint(np.random.randn(50,50))
M = M.dot(M.T)
eig = LA.eigvals(M)
diagMatrix = np.diag(eig)
diagMat = sp.Matrix(diagMatrix)
powerMatrix = matrix_power(diagMatrix,9)
powermat = sp.Matrix(powerMatrix)
powermat

⎡1.10941204389821e+21           0                     0                     0 
⎢                                                                             
⎢         0            6.38716431913932e+20           0                     0 
⎢                                                                             
⎢         0                     0            1.42809789833866e+20           0 
⎢                                                                             
⎢         0                     0                     0            8.640970898
⎢                                                                             
⎢         0                     0                     0                     0 
⎢                                                                             
⎢         0                     0                     0                     0 
⎢                                                                             
⎢         0                     0                   

In [1]:
# Markov matrix & steady state

import numpy as np
from scipy import linalg as LA
from numpy.linalg import matrix_power
import sympy as sp

k = np.array([72, 32, 34])
markov = np.zeros((3,3))
for i in range(0,3):
    m = np.random.rand(1,3)
    m = m/np.sum(m)
    markov[i] = m
for i in range (1,100000):
    base = matrix_power(markov, i)
    base_1 = matrix_power( markov,i+1)
    if (base==base_1).all():
        print("steady state reached for i = %s" % i)
        break
print(markov)
print(base_1)
print(k.dot(base_1))

steady state reached for i = 180
[[0.68991098 0.16168705 0.14840196]
 [0.45741842 0.10102452 0.44155706]
 [0.06250443 0.54703293 0.39046264]]
[[0.44346497 0.26012679 0.29640824]
 [0.44346497 0.26012679 0.29640824]
 [0.44346497 0.26012679 0.29640824]]
[61.19816597 35.89749759 40.90433643]


In [20]:
#DFT & FFT

import numpy as np
from scipy import linalg as LA
from scipy.linalg import dft 
from scipy.fftpack import fft
import sympy as sp
from sympy import init_printing
import time

init_printing()
matrix = np.random.randint(0 , 10000, 2500).reshape(50,50)

tic1 = time.perf_counter()
dft = dft(50).dot(matrix)
toc1 = time.perf_counter()
print("\n DFT took %s seconds\n" % (toc1-tic1))
dft1 = sp.Matrix(dft)
tic1 = time.perf_counter()
fft = fft(matrix)
toc1 = time.perf_counter()
print("\n FFT took %s seconds\n" % (toc1-tic1))
fft1 = sp.Matrix(fft)
fft1


 DFT took 0.0015871549994699308 seconds


 FFT took 0.00013783499980490888 seconds



⎡283886.0  -1594.81634186242 + 3376.86272799534⋅ⅈ  -5968.26391945224 - 886.042
⎢                                                                             
⎢282756.0   31289.0540548834 + 4022.6972587563⋅ⅈ   6164.13662353943 + 21369.88
⎢                                                                             
⎢235037.0  -9060.9536562055 + 22185.0765915278⋅ⅈ   31252.3379110182 - 6908.291
⎢                                                                             
⎢243218.0  28.7760090623615 - 16486.9607085353⋅ⅈ   -2060.11978775591 - 22631.9
⎢                                                                             
⎢252675.0  949.136785804045 + 8561.96045293998⋅ⅈ   -4683.30350133368 - 2158.73
⎢                                                                             
⎢267579.0  9737.84250148813 + 8460.25511929242⋅ⅈ   16277.0233044443 + 21649.18
⎢                                                                             
⎢218402.0  -23640.6376719835 - 731.406102196022⋅ⅈ  3

In [32]:
# check similarity
"""
1) Two matrices A & B will be similar only when they have the same eigen values.
If they have different eigen values , there will be no solution to the equation PA = PB.
We will verify this through a 10* 10 matrix
2) Given a 50 by 50 matrix , how to find a similar matrix ( non diagonal)
Get any invertible 50 by 50 matrix & multiply Pinv. A. P
The resultant matrix should have same eigen values & similar to A
3) Also we can find the similar matrix by multiplying Eigen values with V*VT where V is the column of any orthonormal basis

"""
import numpy as np
from scipy import linalg as LA
from numpy.linalg import inv

np.set_printoptions(suppress=True)
A = np.random.randint(1,100,2500).reshape(50,50)
A = A.dot(A.T)
P = np.random.randn(50,50)
P_inv = inv(P)
eig1 = LA.eigvals(A)
eig1 = np.sort(eig1)

B1 = P_inv.dot(A)
B = B1.dot(P)
eig2 = LA.eigvals(B)
eig2 = np.sort(eig2)

print(np.real(eig1))
print(np.real(eig2))

[      0.61299541      40.5904105      150.63643592     392.60069182
     657.87501648     949.01831848    1216.38304867    2491.66708938
    3648.09011413    3952.4210281     4809.48633337    5248.20360795
    7192.5849483     7410.04138778    7793.48702946    9094.59604975
   11070.56032108   12060.7825494    15127.89983541   15869.9719397
   16560.48048864   18756.06737826   21738.38359667   23493.12505903
   25572.48937707   29250.06848224   29660.39309054   31609.2960214
   36010.29791256   43294.17925211   43985.58804656   46350.16235575
   52338.1365957    53983.69210315   56582.08677284   62584.14695133
   66293.08942119   69362.99060637   69911.60534016   76928.42927365
   83613.02226074   92305.04914814   97898.45891822  100277.73795682
  106072.81046699  111620.01352803  118478.68785976  139401.26194024
  149090.93731188 6342274.80333284]
[      0.61299541      40.5904105      150.63643592     392.60069182
     657.87501648     949.01831848    1216.38304868    2491.66708938


In [102]:
# jordan normal form
from scipy import linalg as LA
import numpy as np
import sympy as sp
from sympy import Matrix
from sympy import init_printing
init_printing()
C = np.eye(50,50)
for i in range (25,50):
    C[i] = C[i]*2
for i in range(0,48):
    k = np.random.randint(0,2)
    if k == 0:
        C[i,i+1] =1
P = np.random.rand(50,50)
p_inv = inv(P)
JMatrix = p_inv.dot(C).dot(P)
eigC, eigV =LA.eig(C)
eigJ, eigK = LA.eig(JMatrix)

print(eigC)
print(eigJ)



[1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j
 1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j
 1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j 2.+0.j 2.+0.j 2.+0.j 2.+0.j 2.+0.j
 2.+0.j 2.+0.j 2.+0.j 2.+0.j 2.+0.j 2.+0.j 2.+0.j 2.+0.j 2.+0.j 2.+0.j
 2.+0.j 2.+0.j 2.+0.j 2.+0.j 2.+0.j 2.+0.j 2.+0.j 2.+0.j 2.+0.j 2.+0.j]
[0.9444812 +0.01623606j 0.9444812 -0.01623606j 0.96194689+0.04365289j
 0.96194689-0.04365289j 0.99151349+0.05740311j 0.99151349-0.05740311j
 1.02396327+0.05299336j 1.02396327-0.05299336j 1.04894381+0.03160911j
 1.04894381-0.03160911j 1.05830266+0.j         1.00000657+0.00001138j
 1.00000657-0.00001138j 0.99998686+0.j         2.00026498+0.000265j
 2.00026498-0.000265j   1.99973502+0.00026496j 1.99973502-0.00026496j
 2.00001596+0.00001103j 2.00001596-0.00001103j 2.00000808+0.00001399j
 2.00000808-0.00001399j 2.00000157+0.00001933j 2.00000157-0.00001933j
 1.99998247+0.0000083j  1.99998247-0.0000083j  1.99998384+0.j
 0.99999995+0.00000011j 

In [126]:
# Singular value decomposition

from scipy import linalg as LA
import numpy as np
from sympy import Matrix
from sympy import init_printing
init_printing(num_columns = 40)

matrix = np.random.randint(1,10,1200).reshape(30,40)
U, Sigma, VT = LA.svd(matrix)
Sigma = np.diag(Sigma)
k = np.zeros((30,10))
Sigma = np.column_stack((Sigma,k))
matrix = sp.Matrix(matrix)
product = U.dot(Sigma).dot(VT)
product = np.round(product , decimals =2)
product = sp.Matrix(product)
matrix == product

True

In [140]:
#psuedo inverse
from scipy import linalg as LA
import numpy as np
from sympy import Matrix
from sympy import init_printing
init_printing(num_columns = 40, use_latex = True)

matrix = np.random.randint(1,10,1200).reshape(30,40)
matrixT = matrix.T
psuInv1 = LA.pinv(matrix)
psuInv2 = LA.pinv(matrixT)
psuInv1s= sp.Matrix(psuInv1)
psuInv2s= sp.Matrix(psuInv2)
psuInv2s


⎡ 0.0347621260473598   -0.007892967530
⎢                                     
⎢-0.00939827777265667  -0.004100980797
⎢                                     
⎢ 0.0178739195484902    -0.02629276039
⎢                                     
⎢ 0.013361909445936     0.002766639567
⎢                                     
⎢0.00706610990410943   -0.000915309686
⎢                                     
⎢ 0.0173298155656955   -0.007195767953
⎢                                     
⎢0.00703094793002901    -0.02660759025
⎢                                     
⎢0.00273006809735709    -0.01336389321
⎢                                     
⎢0.00165993083392746    -0.02775138959
⎢                                     
⎢ -0.042442444454616    0.009120154263
⎢                                     
⎢-0.0632072285610988     0.01046927304
⎢                                     
⎢-0.00684708919079366   0.028216836912
⎢                                     
⎢ 0.0461027298799475   -0.003631224394
⎢                        